apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: ifconfig
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         5
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf
        HTTP_Server   Off

    [INPUT]
        Name tail
        Tag  ifconfig.service
        Parser golang
        Path /var/log/ifconfig-me.log

    [OUTPUT]
        Name        es
        Match       *
        Host        elasticsearch-logging-es-http.logging
        Port        9200
        Index       ifconfig_me
        tls         On
        tls.verify  Off
        HTTP_User   ${ELASTICSEARCH_USER}
        HTTP_Passwd ${ELASTICSEARCH_PASS}

  parsers.conf: |
    [PARSER]
        Name   golang
        Format regex
        Regex  ^(?<message>.*)$
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z
