---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ifconfig.me
  namespace: ifconfig
  labels:
    app: ifconfig.me
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ifconfig.me
  template:
    metadata:
      labels:
        app: ifconfig.me
    spec:
      tolerations:
      # this toleration is to have the daemonset runnable on master nodes
      # remove it if your masters can't run pods
      # - key: node-role.kubernetes.io/master
      #   effect: NoSchedule
      containers:
      - name: ifconfig
        image: patrickfmarques/ifconfig.me:latest
        resources:
          limits:
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: LOG_FILENAME
          value: /var/log/ifconfig-me.log
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
        - name: log-storage
          mountPath: /var/log/
      - name: log-collector
        image: fluent/fluent-bit:1.7.9
        env:
        - name: ELASTICSEARCH_USER
          valueFrom:
            secretKeyRef:
              name: elastic-credentials
              key: elastic_username
        - name: ELASTICSEARCH_PASS
          valueFrom:
            secretKeyRef:
              name: elastic-credentials
              key: elastic_password
        volumeMounts:
        - name: log-storage
          mountPath: /var/log/
          readOnly: true
        - name: fluent-bit-config
          mountPath: /fluent-bit/etc/
      terminationGracePeriodSeconds: 30
      volumes:
      - name: log-storage
        emptyDir: {}
      - name: fluent-bit-config
        configMap:
          name: fluent-bit-config

---
apiVersion: v1
kind: Service
metadata:
  name: ifconfig-service
  namespace: ifconfig
  labels:
    app: ifconfig.me
spec:
  ports:
  - port: 8080
    targetPort: http
    protocol: TCP
  selector:
    app: ifconfig.me
