---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: ifconfig
spec:
  podSelector:
    matchLabels:
      app: ifconfig.me
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Allow connections from the ingress only
  - from:
    - podSelector:
        matchLabels:
          # app.kubernetes.io/name: ingress-nginx
          app.kubernetes.io/component: controller
      namespaceSelector:
        matchLabels:
          app.kubernetes.io/name: ingress-nginx
    ports:
    - protocol: TCP
      port: 80
  egress:
  - to:
    - podSelector:
        matchLabels:
          common.k8s.elastic.co/type: elasticsearch
          elasticsearch.k8s.elastic.co/cluster-name: elasticsearch-logging
      namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: logging
    ports:
    - protocol: TCP
      port: 9200
